### ISSUE TITLE
How is preview kit supposed to be used within a project using presentation mode? 

### ISSUE THREAD

**Issue by amlcodes** [sanity-io/preview-kit#789]
**Describe the bug**

following the presentation guide in the sanity docs to update a project already using preview-kit and livequeryprovider fails because of the additional security advice to use 

experimental_taintUniqueValue(
  'Do not pass the sanity API read token to the client.',
  process,
  token,
)

since we are passing token to livequeryprovider.

**Expected behavior**

The docs are very disjointed are unclear, especially when updating preview methods. I'm not sure if I can use presentation mode for higher view editing and previewing , and preview mode on documents to enable the same flow directly from the document or werever I specify in the structure. I'd expect to be able to use both.

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by stipsan** [comment]
Hi,

The security advice is only applicable to when you're not using `preview-kit`. It's part of the `preview-kit` architecture to setup an authenticated sanity client instance outside of a  Studio application, that can then listen to updates and respond to them live.

When a project is using the new `@sanity/react-loader` and its live mode the reason why we issue this guidance is because it doesn't use the `token` in your app, it is instead using the authenticated client instance in the Studio to run live queries and then post updates back to your app using [the `postMessage` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).

I recommend looking at our official template that follows all our best practices for using `sanity/presentation` with `preview-kit`: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3

**Comment by amlcodes** [comment]
What is the recommendation to users? Is preview mode not being promoted, pointing to people to use presentation mode instead? Is react-loader's live mode compatible with preview or only presentation?
